#!/bin/sh
mvn clean package && docker build -t nj9666/JWTResorce .
docker rm -f JWTResorce 2>/dev/null || true && docker run -it --name JWTResorce -p 8080:8080 -p 4848:4848 -p 8181:8181 --name JWTResorce nj9666/JWTResorce
